services:
  app:
    build: .
    container_name: docker_spring_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/java_fish
      - SPRING_DATASOURCE_USERNAME=java_fish_admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_PROFILES_ACTIVE=docker

  db:
    container_name: docker_postgres_db
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=java_fish
      - POSTGRES_USER=java_fish_admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  postgres_data: